CREATE TABLE [dbo].[ImageLike] (
    [ID]      INT IDENTITY (1, 1) NOT NULL,
    [ImageID] INT NOT NULL,
    [UserID]  INT NOT NULL,
    [IsLike]  BIT NOT NULL,
    CONSTRAINT [PK_ImageLike] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ImageLike_Image] FOREIGN KEY ([ImageID]) REFERENCES [dbo].[Image] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_ImageLike_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

