CREATE TABLE [dbo].[ImageLink] (
    [ID]      INT IDENTITY (1, 1) NOT NULL,
    [ImageID] INT NOT NULL,
    [LinkID]  INT NOT NULL,
    CONSTRAINT [PK_ImageLink] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_ImageLink_Image] FOREIGN KEY ([ImageID]) REFERENCES [dbo].[Image] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_ImageLink_Link] FOREIGN KEY ([LinkID]) REFERENCES [dbo].[Link] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

