CREATE TABLE [dbo].[PersonRegion] (
    [ID]       INT IDENTITY (1, 1) NOT NULL,
    [PersonID] INT NOT NULL,
    [RegionID] INT NOT NULL,
    CONSTRAINT [PK_PersonRegion] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PersonRegion_Person] FOREIGN KEY ([PersonID]) REFERENCES [dbo].[Person] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PersonRegion_Region] FOREIGN KEY ([RegionID]) REFERENCES [dbo].[Region] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

