CREATE TABLE [dbo].[PersonLink] (
    [ID]       INT IDENTITY (1, 1) NOT NULL,
    [PersonID] INT NOT NULL,
    [LinkID]   INT NOT NULL,
    CONSTRAINT [PK_PersonLink] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_PersonLink_Link] FOREIGN KEY ([LinkID]) REFERENCES [dbo].[Link] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_PersonLink_Person] FOREIGN KEY ([PersonID]) REFERENCES [dbo].[Person] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

